image: archlinux
packages:
  - rustup
  - nodejs
  - npm
  - tar
sources:
  - https://git.sr.ht/~verfassungsblog/Verfassungsbooks
tasks:
  - setup: |
      rustup default stable
      npm config set prefix ~/.npm
      mkdir -p ~/.npm/bin
      echo 'export PATH="$HOME/.npm/bin:$PATH"' >> ~/.bashrc
      npm install -g handlebars
      npm install -g typescript
      npm install -g webpack webpack-cli
      cd Verfassungsbooks/typescript
      npm install
  - build: |
      branch_name=$(echo $GIT_REF | rev | cut -d'/' -f1 | rev)
      source ~/.bashrc
      handlebars -v
      cd Verfassungsbooks
      cargo build --release
      echo "$branch_name-$(git rev-parse --short HEAD)" > version.txt
  - packaging: |
      cd Verfassungsbooks
      mkdir packaged
      cp target/release/Verfassungsbooks packaged/
      mkdir -p packaged/config
      cp config/default.toml packaged/config/
      cp Rocket.toml packaged/
      cp version.txt packaged/
      cp -R static packaged/static
      tar -czf verfassungsbooks-bundled.tar.gz packaged/
artifacts:
  - Verfassungsbooks/verfassungsbooks-bundled.tar.gz
triggers:
  - action: email
    condition: failure
    to: kd@verfassungsblog.de