image: archlinux
packages:
  - rustup
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~verfassungsblog/Verfassungsbooks
tasks:
  - env-setup: |
      branch_name=$(echo $GIT_REF | rev | cut -d'/' -f1 | rev)
      echo "Branch name: $branch_name"
  - setup: |
      rustup default stable
      npm config set prefix ~/.npm
      mkdir -p ~/.npm/bin
      echo 'export PATH=~/.npm/bin/:$PATH' >> ~/.bashrc
      npm install -g handlebars
  - build: |
      cd Verfassungsbooks
      cargo build --release
artifacts:
  - Verfassungsbooks/target/release/Verfassungsbooks
  - Verfassungsbooks/config/default.toml
  - Verfassungsbooks/Rocket.toml