[package]
name = "Verfassungsbooks"
version = "0.1.0"
edition = "2021"
authors = ["Keanu Dölle <kd@verfassungsblog.de>"]
repository = "https://github.com/Verfassungsblog/verfassungsbooks"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "=0.5.0-rc.4", features = ["secrets"] }
diesel = { version = "2.1.0", features = ["mysql"] }
dotenvy = "0.15"
config = "0.13.1"
serde = "1.0.192"
serde_derive = "1.0.192"
rand = "0.8.5"
rocket_dyn_templates = { version = "=0.1.0-rc.4", features = ["handlebars"] }
argon2 = "0.5.2"