[default]
address = "0.0.0.0"
port = 8008
limits = { form = "100 MiB", data-form = "100 MiB", file = "100 MiB", json = "1 MiB" }
secret_key = "J28tNwSvc9xS2TK5zMFSmmAXVZpCQVbdzxL0PeNl3wGnkWzf2tBtxwBUW/MSg7kQ65wrDjBLCbzZ8K7RLYXAng=="

[debug]
address = "127.0.0.1"
port = 8000
