app_title = "Verfassungsbooks"
project_cache_time = 1800
#WARNING: CURRENTLY NOT USED IN ALL PLACES, leave it on data for now
data_path = "data"
# Time until data storage write fails in ms
file_lock_timeout = 1000
# Time until in-memory database is written to file in seconds
backup_to_file_interval = 20
# Maximum number of concurrent rendering threads
max_connections_to_rendering_server = 10
# Maximum number of concurrent import processing threads
max_import_threads = 4
# URL to the zotero translation server (https://github.com/zotero/translation-server) for importing zotero items.
zotero_translation_server = "https://translation-server.anghenfil.de"

# Export Server Settings

# mTLS CA Cert
ca_cert_path = "certs/root.crt"
# mTLS Cert
client_cert_path = "certs/client.crt"
# mTLS Cert key
client_key_path = "certs/client.key"
# mTLS revocation list
revocation_list_path = "certs/crl.der"

# List of Export servers.
[[export_servers]]
hostname = "[::1]"
port = 6969
domain_name = "localhost"

# Example second export server:
# [[export_servers]]
# hostname = "1.2.3.4"
# port = 5050
# domain_name = "example.com"