app_title = "Verfassungsbooks"
project_cache_time = 1800
data_path = "data"
# Time until data storage write fails in ms
file_lock_timeout = 1000
# Time until in-memory database is written to file in seconds
backup_to_file_interval = 20
# Maximum number of concurrent rendering threads
max_rendering_threads = 10
# Maximum number of concurrent import processing threads
max_import_threads = 4
# Optional: Path to chromium executable, set to empty string to use included chromium, but it doesn't work for alpine.
chromium_path = "/usr/bin/chromium-browser"
# URL to the zotero translation server (https://github.com/zotero/translation-server) for importing zotero items.
zotero_translation_server = "https://translation-server.anghenfil.de"