app_title = "Verfassungsbooks"
project_cache_time = 1800
data_path = "data"
# Time until data storage write fails in ms
file_lock_timeout = 1000
# Time until in-memory database is written to file in seconds
backup_to_file_interval = 20